//webpack.config.js
module.exports={
	devtool:'eval-source-map',
	entry:__dirname+'/src/index.js',
	output:{
		path:__dirname+'/src/public',
		filename:'bundle.js'
	},
	devServer:{
		contentBase:'./src/public',
		inline:true,
		historyApiFallback:true
	},
	module:{
		rules:[
		{
			test:/(\.jsx|\.js)$/,
			use:{
				loader:'babel-loader',
			},
			exclude:/node_modules/
		},{
			test:/\.css$/,
			use:[
                {
                	loader:'style-loader'
                },{
                	loader:'css-loader'
                }
			]
		}
		]
	},
	plugins:[
	]
};